jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - continue-on-error: true
      id: previoustag
      name: Get Previous tag
      uses: WyriHaximus/github-action-get-previous-tag@v1
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        cache: maven
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: replace version
      run: ver=${{ steps.previoustag.outputs.tag }} && new_ver=${ver:1} && sed -i
        "s/SONIC_VERSION/${new_ver}/g" pom.xml
    - continue-on-error: true
      name: login docker hub
      run: echo "${{ secrets.ACCESS_TOKEN }}" | docker login -u zhouyixun --password-stdin
    - continue-on-error: true
      run: rm -rf plugins/sonic-android-apk.apk
    - continue-on-error: true
      name: saa-download
      uses: robinraju/release-downloader@v1.4
      with:
        fileName: sonic-android-apk.apk
        latest: true
        repository: SonicCloudOrg/sonic-android-apk
    - continue-on-error: true
      name: saa
      run: mv sonic-android-apk.apk plugins/sonic-android-apk.apk
    - continue-on-error: true
      name: sas-download
      uses: robinraju/release-downloader@v1.4
      with:
        fileName: '*_linux_x86_64.tar.gz'
        latest: true
        repository: SonicCloudOrg/sonic-android-supply
    - continue-on-error: true
      name: sas
      run: tar zxvf *_linux_x86_64.tar.gz && rm *_linux_x86_64.tar.gz && mv sas plugins/sonic-android-supply
    - continue-on-error: true
      name: sgm-download
      uses: robinraju/release-downloader@v1.4
      with:
        fileName: '*_linux_x86_64.tar.gz'
        latest: true
        repository: SonicCloudOrg/sonic-go-mitmproxy
    - continue-on-error: true
      name: sgm
      run: tar zxvf *_linux_x86_64.tar.gz && rm *_linux_x86_64.tar.gz && mv sonic-go-mitmproxy
        plugins/sonic-go-mitmproxy
    - continue-on-error: true
      name: sib-download
      uses: robinraju/release-downloader@v1.4
      with:
        fileName: '*_linux_x86_64.tar.gz'
        latest: true
        repository: SonicCloudOrg/sonic-ios-bridge
    - continue-on-error: true
      name: sib
      run: tar zxvf *_linux_x86_64.tar.gz && rm *_linux_x86_64.tar.gz && mv sib plugins/sonic-ios-bridge
    - continue-on-error: true
      name: deploy
      run: mvn package -Dplatform=linux-x86_64 -Dmaven.test.skip=true
    - continue-on-error: true
      name: build image
      run: docker build -t sonicorg/sonic-agent-linux:${{ steps.previoustag.outputs.tag
        }} -f src/main/docker/Dockerfile .
    - continue-on-error: true
      name: push
      run: docker push sonicorg/sonic-agent-linux:${{ steps.previoustag.outputs.tag
        }}
name: deploy to Dockerhub
on:
  repository_dispatch:
    types: trigger-ga___deploy.yml
