jobs:
  create:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: softprops/action-gh-release@v1
      with:
        draft: false
        generate_release_notes: true
  doc:
    needs: create
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - continue-on-error: true
      id: previoustag
      name: Get Previous tag
      uses: WyriHaximus/github-action-get-previous-tag@v1
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        cache: maven
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: replace version
      run: sed -i "s/SONIC_VERSION/${{ steps.previoustag.outputs.tag }}/g" src/main/docker/docker-compose*.yml
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Upload yml To Github Release
      uses: xresloader/upload-to-github-release@v1.3.4
      with:
        draft: false
        file: src/main/docker/docker-compose.yml;src/main/docker/docker-compose-zh.yml
        tag_name: ${{ steps.previoustag.outputs.tag }}
        update_latest_release: true
  release:
    needs: create
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - continue-on-error: true
      id: previoustag
      name: Get Previous tag
      uses: WyriHaximus/github-action-get-previous-tag@v1
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        cache: maven
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: replace version
      run: ver=${{ steps.previoustag.outputs.tag }} && new_ver=${ver:1} && sed -i
        "s/SONIC_VERSION/${new_ver}/g" pom.xml && sed -i "s/SONIC_VERSION/${{ steps.previoustag.outputs.tag
        }}/g" src/main/docker/docker-compose*.yml
    - continue-on-error: true
      name: mkdir
      run: mkdir -p sonic-agent-${{ steps.previoustag.outputs.tag }}-${{matrix.depend}}/plugins
    - continue-on-error: true
      name: package
      run: mvn clean package -Dplatform=${{ matrix.platform }} -Dmaven.test.skip=true
    - continue-on-error: true
      name: mvJar-linux86
      run: cp -r target/sonic-agent-${{ matrix.platform }}.jar sonic-agent-${{ steps.previoustag.outputs.tag
        }}-${{matrix.depend}}/
    - continue-on-error: true
      name: copy
      run: cp -r config/ mini/ sonic-agent-${{ steps.previoustag.outputs.tag }}-${{matrix.depend}}/
    - continue-on-error: true
      name: adb-download
      uses: robinraju/release-downloader@v1.4
      with:
        fileName: '*'
        latest: true
        repository: SonicCloudOrg/sonic-adb-binary
    - continue-on-error: true
      name: adb-unzip
      run: unzip platform-tools_r34.0.3-${{matrix.adb}}.zip && mv platform-tools/*
        sonic-agent-${{ steps.previoustag.outputs.tag }}-${{matrix.depend}}/plugins/
    - continue-on-error: true
      name: sas-download
      uses: robinraju/release-downloader@v1.4
      with:
        fileName: '*'
        latest: true
        repository: SonicCloudOrg/sonic-android-supply
    - continue-on-error: true
      name: sas-untar
      run: tar zxvf *_${{matrix.depend}}.tar.gz && rm *_${{matrix.depend}}.tar.gz
        && mv sas${{matrix.tail}} sonic-agent-${{ steps.previoustag.outputs.tag }}-${{matrix.depend}}/plugins/sonic-android-supply${{matrix.tail}}
    - continue-on-error: true
      name: sgm-download
      uses: robinraju/release-downloader@v1.4
      with:
        fileName: '*'
        latest: true
        repository: SonicCloudOrg/sonic-go-mitmproxy
    - continue-on-error: true
      name: sgm-untar
      run: tar zxvf *_${{matrix.depend}}.tar.gz && rm *_${{matrix.depend}}.tar.gz
        && mv sonic-go-mitmproxy${{matrix.tail}} sonic-agent-${{ steps.previoustag.outputs.tag
        }}-${{matrix.depend}}/plugins/sonic-go-mitmproxy${{matrix.tail}}
    - continue-on-error: true
      name: sib-download
      uses: robinraju/release-downloader@v1.4
      with:
        fileName: '*'
        latest: true
        repository: SonicCloudOrg/sonic-ios-bridge
    - continue-on-error: true
      name: sib-untar
      run: tar zxvf *_${{matrix.depend}}.tar.gz && rm *_${{matrix.depend}}.tar.gz
        && mv sib${{matrix.tail}} sonic-agent-${{ steps.previoustag.outputs.tag }}-${{matrix.depend}}/plugins/sonic-ios-bridge${{matrix.tail}}
    - continue-on-error: true
      name: saa-download
      uses: robinraju/release-downloader@v1.4
      with:
        fileName: sonic-android-apk.apk
        latest: true
        repository: SonicCloudOrg/sonic-android-apk
    - continue-on-error: true
      name: saa
      run: cp sonic-android-apk.apk sonic-agent-${{ steps.previoustag.outputs.tag
        }}-${{matrix.depend}}/plugins/
    - continue-on-error: true
      name: sas
      run: cp plugins/sonic-android-scrcpy.jar sonic-agent-${{ steps.previoustag.outputs.tag
        }}-${{matrix.depend}}/plugins/
    - continue-on-error: true
      name: appium1
      run: cp plugins/sonic-appium-uiautomator2-server.apk sonic-agent-${{ steps.previoustag.outputs.tag
        }}-${{matrix.depend}}/plugins/
    - continue-on-error: true
      name: appium2
      run: cp plugins/sonic-appium-uiautomator2-server-test.apk sonic-agent-${{ steps.previoustag.outputs.tag
        }}-${{matrix.depend}}/plugins/
    - continue-on-error: true
      name: zip
      uses: TheDoctor0/zip-release@0.6.2
      with:
        directory: sonic-agent-${{ steps.previoustag.outputs.tag }}-${{matrix.depend}}
        filename: sonic-agent-${{ steps.previoustag.outputs.tag }}-${{matrix.depend}}.zip
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Upload Zip To Github Release
      uses: xresloader/upload-to-github-release@v1.3.4
      with:
        draft: false
        file: sonic-agent-${{ steps.previoustag.outputs.tag }}-${{matrix.depend}}/sonic-agent-${{
          steps.previoustag.outputs.tag }}-${{matrix.depend}}.zip
        tag_name: ${{ steps.previoustag.outputs.tag }}
        update_latest_release: true
    strategy:
      matrix:
        include:
        - adb: linux
          depend: linux_x86
          platform: linux-x86
        - adb: linux
          depend: linux_x86_64
          platform: linux-x86_64
        - adb: linux
          depend: linux_arm64
          platform: linux-arm64
        - adb: darwin
          depend: macosx_x86_64
          platform: macosx-x86_64
        - adb: darwin
          depend: macosx_arm64
          platform: macosx-arm64
        - adb: windows
          depend: windows_x86
          platform: windows-x86
          tail: .exe
        - adb: windows
          depend: windows_x86_64
          platform: windows-x86_64
          tail: .exe
        platform:
        - windows-x86
        - windows-x86_64
        - macosx-arm64
        - macosx-x86_64
        - linux-arm64
        - linux-x86
        - linux-x86_64
name: release to github
on:
  repository_dispatch:
    types: trigger-ga___release.yml
